//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TERA_2016 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class dbSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static dbSettings defaultInstance = ((dbSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new dbSettings())));
        
        public static dbSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db_tera")]
        public string dbName {
            get {
                return ((string)(this["dbName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT roles.id, roles.name FROM roles\r\n  ORDER BY roles.id ASC")]
        public string selectRoles {
            get {
                return ((string)(this["selectRoles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"  select users.id, users.last_name, users.name, users.third_name, users.employee_number, users.password, roles.name as role_name from users LEFT JOIN roles ON (users.role_id = roles.id) WHERE users.is_active = 1 AND users.role_id > 1 
  ORDER BY users.last_name ASC")]
        public string selectActiveUsersJoinedRoles {
            get {
                return ((string)(this["selectActiveUsersJoinedRoles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO users (users.last_name, users.name, users.third_name, users.password," +
            " users.employee_number, users.role_id, users.is_active) VALUES(\"{0}\",\"{1}\",\"{2}\"" +
            ",\"{3}\",{4},{5}, 1)")]
        public string insertUser {
            get {
                return ((string)(this["insertUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE users SET users.is_active = 0 \r\n\tWHERE users.id IN({0})")]
        public string hideUsers {
            get {
                return ((string)(this["hideUsers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE users SET users.name = \"{1}\", users.last_name = \"{2}\", users.third_name = " +
            "\"{3}\", users.employee_number = {4}, users.role_id = {5}, users.password = \"{6}\" " +
            "WHERE users.id IN({0})")]
        public string updateUserWithPassword {
            get {
                return ((string)(this["updateUserWithPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE users SET users.name = \"{1}\", users.last_name = \"{2}\", users.third_name = " +
            "\"{3}\", users.employee_number = {4}, users.role_id = {5} WHERE users.id IN({0})")]
        public string updateUserWithoutPassword {
            get {
                return ((string)(this["updateUserWithoutPassword"]));
            }
        }
    }
}
